version: "3"
services:
    qemu:
        container_name: qemu
        image: qemux/qemu-docker:latest
        environment:
            DISPLAY: "vnc"
            RAM_SIZE: "1G"
            CPU_CORES: "1"
            DISK_SIZE: "16G"
            BOOT: "https://dl-cdn.alpinelinux.org/alpine/v3.18/releases/x86_64/alpine-standard-3.18.2-x86_64.iso"
        devices:
            - /dev/kvm
            - /dev/net/tun
            - /dev/vhost-net
        device_cgroup_rules:
            - 'c *:* rwm'
        cap_add:
            - NET_ADMIN              
        ports:
            - 2222:22
            - 5900:5900
        restart: on-failure
        stop_grace_period: 1m
