version: "3"
services:
  qemu:
    container_name: openwrt
    #image: albrechtloh/qemu-openwrt:openwrt-23.05.2-10
    image: "openwrt-docker-arm64"

    environment:
      DEBUG: "y"

      # Define number of VM CPUs
      CPU_COUNT: 2

      # Define which physical or virtual interfaces shall be attach direct to OpenWrt
      #WAN_IF: "enx00e04c0407a6"
      #LAN_IF: "enx00e04d68033f"
      #LAN_IF: "veth" # veth pair between OpenWrt and host system
      #FORWARD_LUCI: "true" # Make LuCI OpenWrt web interface accessible via host LAN

      # USB passthrough
      # Format <vendorID>:<productID> like 'lsusb' is given
      # Currently only one USB device is supported
      #USB_VID_1: "0e8d" # vendor ID
      #USB_PID_1: "7961" # product ID

    ports:
      # Port 8006 is console tty web VNC
      - 8006:8006
      # Port 8000 is available only when Docker WAN network is used.
      # Use script /usr/bin/fw_wan_open_http to open the port
      - 8000:8000
      # SSH
      # Use script /usr/bin/fw_wan_open_ssh to open the port
      - 8022:8022
    stop_grace_period: 2m
    restart: on-failure
    
    # The following settings are mandantory to run the container
    devices:
      - /dev/kvm
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    pid: "host"
    privileged: true
    volumes:
      - /dev:/dev/
      - data:/storage/

volumes:
  data: