version: "3"
services:
  qemu:
    container_name: openwrt-docker-arm64
    image: "openwrt-docker-arm64"
    environment:
      DEBUG: "y"
      # If WAN interface is not specified the Docker network
      # In this case a port forwarding from port OpenWrt 80 to port 8000 is available
      #WAN_IF: "enx00e04c0407a6"
      #LAN_IF: "enx00e04d68033f"
    devices:
      - /dev/kvm
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      # Port 8000 is available only when Docker WAN network is used.
      # Use script /root/fw_wan_open_http.sh to open the port
      - 8000:8000
    stop_grace_period: 2m
    restart: on-failure
    pid: "host"
    privileged: true
    volumes:
      - /dev:/dev/
