version: "3"
services:
    vm:
        container_name: qemu
        image: kroese/docker-qemu:latest
        environment:
            CPU_CORES: "1"
            RAM_SIZE: "512M"            
            DISK_SIZE: "16G"
            BOOT: "http://archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/current/legacy-images/netboot/mini.iso"
        devices:
            - /dev/kvm
        cap_add:
            - NET_ADMIN                       
        ports:
            - 22:22
        restart: on-failure

