version: "3"
services:
    vm:
        container_name: qemu
        image: kroese/docker-qemu:latest
        environment:
            CPU_CORES: "1"
            RAM_SIZE: "512M"            
            DISK_SIZE: "16G"
            BOOT: "http://www.tinycorelinux.net/13.x/x86/release/Core-13.1.iso"
        devices:
            - /dev/kvm
        cap_add:
            - NET_ADMIN                       
        ports:
            - 22:22
        restart: on-failure

