version: "3"
services:
  qemu:
    container_name: openwrt-docker-arm64
    image: "openwrt-docker-arm64"
    environment:
      DEBUG: "y"
      WAN_IF: "enx00e04c0407a6"
      LAN_IF: "enx00e04d68033f"
    devices:
      - /dev/kvm
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    stop_grace_period: 2m
    restart: on-failure
    pid: "host"
    privileged: true
    volumes:
      - /dev:/dev/
