version: "3"
services:
    vm:
        container_name: qemu
        image: kroese/docker-qemu:latest
        environment:
            CPU_CORES: "1"
            RAM_SIZE: "512M"            
            DISK_SIZE: "16G"            
        devices:
            - /dev/kvm
        cap_add:
            - NET_ADMIN                       
        ports:
            - 22:22
            - 80:80
        restart: on-failure
        stop_grace_period: 60s
