name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '.gitignore'
      - '.dockerignore'
      - '.github/**'
      - '.github/workflows/**'
  
concurrency:
  group: build
  cancel-in-progress: false

jobs:
  shellcheck:
    name: Test
    uses: ./.github/workflows/check.yml
  build:
    name: Build
    needs: shellcheck
    runs-on: ubuntu-latest
    permissions:
      actions: write
      packages: write
      contents: read
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build Docker image
        id: build
        run: |
        
          PLATFORMS="linux/amd64,linux/arm64"
          VERSION="${{ vars.MAJOR }}.${{ vars.MINOR }}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
   
          TAGS=()
          TAGS=("${{ secrets.DOCKERHUB_REPO }}:latest")
          TAGS+=("${{ secrets.DOCKERHUB_REPO }}:${VERSION}")
          TAGS+=("ghcr.io/${{ github.repository }}:latest")
          TAGS+=("ghcr.io/${{ github.repository }}:${VERSION}")

          docker buildx build --platform ${PLATFORMS} \
            --output "type=image,push=true" \
            --progress=plain \
            --build-arg "BUILD_ARG=${GITHUB_RUN_ID}" \
            --build-arg "VERSION_ARG=${VERSION}" \
            --build-arg "DATE_ARG=${BUILD_DATE}" \
            --build-arg "VCS_REF=${GITHUB_SHA::8}" \
            $(printf "%s" "${TAGS[@]/#/ --tag }" ) .
      -
        name: Create a release
        uses: action-pack/github-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          tag: "v${{ steps.build.outputs.version }}"
          title: "v${{ steps.build.outputs.version }}"
      -
        name: Increment version variable
        uses: action-pack/bump@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Push to Gitlab mirror
        uses: action-pack/gitlab-sync@v3
        with:
          url: ${{ secrets.GITLAB_URL }}
          token: ${{ secrets.GITLAB_TOKEN }}
          username: ${{ secrets.GITLAB_USERNAME }}    
