on:
  push:
    branches-ignore:
      - master
    paths:
      - '**/*.sh'

  pull_request:
    paths:
      - '**/*.sh'

name: "Test"
permissions: {}

jobs:
  Shellcheck:
    uses: ./.github/workflows/check.yml
